# Generated by Django 4.2.7 on 2023-11-06 12:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('count_reports', models.IntegerField()),
                ('url_report', models.CharField(max_length=150)),
                ('count_threads', models.IntegerField()),
            ],
        ),
    ]
