# Generated by Django 4.2.7 on 2023-11-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_site_tg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('user_agent', models.TextField()),
                ('mail', models.TextField()),
                ('report_text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='reports',
            field=models.ManyToManyField(to='report_site_tg.report'),
        ),
    ]
