# Generated by Django 4.2.7 on 2023-11-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_site_tg', '0003_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='proxy',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
